substitutions:
  _REGION: europe-west6
  _REPOSITORY: xray-repo
  _SERVICE: xray-ui
  _IMAGE: europe-west6-docker.pkg.dev/project-a5834adc-8f24-44e6-8f1/${_REPOSITORY}/${_SERVICE}

# Cloud Build builds Docker images, pushes to Artifact Registry, deploys Cloud Run.

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: build-ui
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/Dockerfile.ui
      - -t
      - ${_IMAGE}:$COMMIT_SHA
      - .

  - id: push-ui
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}:$COMMIT_SHA

  - id: deploy-ui
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --quiet

images:
  - ${_IMAGE}:$COMMIT_SHA
