steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'docker/Dockerfile.train',
      '-t', 'europe-west4-docker.pkg.dev/project-a5834adc-8f24-44e6-8f1/xray-abnormality-detector-eu/xray-train:latest',
      '.'
    ]
images:
  - 'europe-west4-docker.pkg.dev/project-a5834adc-8f24-44e6-8f1/xray-abnormality-detector-eu/xray-train:latest'
