FROM python:3.11-slim

WORKDIR /app

ENV XRAY_API_URL=http://api:8080/predict \
    STREAMLIT_SERVER_ADDRESS=0.0.0.0 \
    STREAMLIT_SERVER_PORT=8080

COPY ui/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ui/ ./ui/

EXPOSE 8080

# Executes streamlit_app.py
CMD ["streamlit", "run", "ui/streamlit_app.py", "--server.port=8080", "--server.address=0.0.0.0"]
