FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install dvc-gs

COPY src/ ./src/
COPY configs/ ./configs/

ENV PYTHONPATH=/app

CMD ["python", "src/training/train.py"]