FROM python:3.11-slim

WORKDIR /app

ENV XRAY_API_URL=http://api:8000/predict \
    STREAMLIT_SERVER_ADDRESS=0.0.0.0 \
    STREAMLIT_SERVER_PORT=8501

    # Loads less dependencies than in the main requirements.txt
COPY ui/requirements.txt ./requirements.txt 
RUN pip install --no-cache-dir -r requirements.txt

COPY ui/ ./ui/

EXPOSE 8501

# Executes streamlit_app.py
CMD ["streamlit", "run", "ui/streamlit_app.py"] 
